# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9
language: objective-c
xcode_workspace: XSafeAccess.xcworkspace
xcode_scheme: XSafeAccess

cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild test -workspace Example/XSafeAccess.xcworkspace -scheme XSafeAccess-Example | xcpretty
# - pod lib lint